---
title: "R Notebook"
output: html_notebook
---



Maxmimum Likelihood

cd /Applications/raxml-ng_v1.2.1_macos_x86_64

We are following HAL 1.3.

Download raxml-ng from here. You get a zipped folder: raxml-ng_v1.0.2_macos_x86_64 which I placed in my /Applications folder

##Reminders 
# branch lengths do not have to do with time
# need outgroup in order to root tree
# otherwise ML will root randomly among the taxa presented


#Checking the version

cd /Applications/raxml-ng_v1.2.1_macos_x86_64
./raxml-ng -v


#RAxML-NG v. 1.2.1 released on 22.12.2023 by The Exelixis Lab.
#Developed by: Alexey M. Kozlov and Alexandros Stamatakis.
#Contributors: Diego Darriba, Tomas Flouri, Benoit Morel, Sarah Lutteropp, Ben Bettisworth, Julia Haag, Anastasis #Togkousidis.
#Latest version: https://github.com/amkozlov/raxml-ng
#Questions/problems/suggestions? Please visit: https://groups.google.com/forum/#!forum/raxml

#DO I need to run this check on my file?

#Check for the MSA:

## This is a bad file and gives errors with the results
./raxml-ng --check --msa ng-tutorial/bad.fa --model GTR+G

./raxml-ng --check --msa ng-tutorial/bad.fa --model GTR+G

#Rerun the MSA check for the corrected file:

./raxml-ng --check --msa ng-tutorial/bad.fa.raxml.reduced.phy --model GTR+G



#We will do the check on a larger file with 12 taxa and 898 sites. For this case, raxml recommends that we use the --parse option to compress the sequences for efficient use in raxml:

./raxml-ng --parse --msa ng-tutorial/prim.phy --model GTR+G

--------------

check:

./raxml-ng --check --msa /Users/jacquelinelemaire/Documents/phylo_class/phylo_class/analysis/cyano_76/hmmsearch/rp16/alignment-files-all/concatenated-alignment/rp_concat_15_curated_mask30.fasta --model PROTGTR+G --prefix A1

#output:
NOTE: Reduced alignment (with duplicates and gap-only sites/taxa removed)
NOTE: was saved to: /Applications/raxml-ng_v1.2.1_macos_x86_64/A1.raxml.reduced.phy

Alignment comprises 1 partitions and 2364 sites

Partition 0: noname
Model: PROTGTR+FO+G4m
Alignment sites: 2364
Gaps: 7.89 %
Invariant sites: 36.46 %



Alignment can be successfully read by RAxML-NG.


Execution log saved to: /Applications/raxml-ng_v1.2.1_macos_x86_64/A1.raxml.log

Analysis started: 30-Apr-2024 18:26:41 / finished: 30-Apr-2024 18:26:41

Elapsed time: 0.017 seconds

./raxml-ng --bootstrap --msa /Applications/raxml-ng_v1.2.1_macos_x86_64/A1.raxml.reduced.phy --model PROTGTR+G --prefix A2 --threads 2 --seed 2 --tree pars{25},rand{25}

output:

Analysis options:
  run mode: Bootstrapping
  start tree(s): random (25) + parsimony (25)
  bootstrap replicates: parsimony (max: 1000) + bootstopping (autoMRE, cutoff: 0.030000)
  random seed: 2
  tip-inner: OFF
  pattern compression: ON
  per-rate scalers: OFF
  site repeats: ON
  logLH epsilon: general: 10.000000, brlen-triplet: 1000.000000
  fast spr radius: AUTO
  spr subtree cutoff: 1.000000
  fast CLV updates: ON
  branch lengths: proportional (ML estimate, algorithm: NR-FAST)
  SIMD kernels: SSE3
  parallelization: coarse-grained (auto), PTHREADS (2 threads), thread pinning: OFF

[00:00:00] Reading alignment from file: /Applications/raxml-ng_v1.2.1_macos_x86_64/A1.raxml.reduced.phy
[00:00:00] Loaded alignment with 60 taxa and 2364 sites

Alignment comprises 1 partitions and 1776 patterns

Partition 0: noname
Model: PROTGTR+FO+G4m
Alignment sites / patterns: 2364 / 1776
Gaps: 7.89 %
Invariant sites: 36.46 %


NOTE: Binary MSA file created: A2.raxml.rba

Parallelization scheme autoconfig: 1 worker(s) x 2 thread(s)

Parallel reduction/worker buffer size: 1 KB  / 0 KB

[00:00:00] Data distribution: max. partitions/sites/weight per thread: 1 / 888 / 71040
[00:00:00] Data distribution: max. searches per worker: 1000
[00:00:00] Starting bootstrapping analysis with 1000 replicates.

